name: Nienke Alberts
favicon: null
layout_spectrum: 0.12507092650048435
typography_spectrum: 0.020632718224078417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9911957082804292
  lightness: 0.26375954900868237
  saturation: 0.6521854093298316
  rhythmicContrast: 0.8041013216134161
purpose: []
