name: Nienke Alberts
favicon: null
layout_spectrum: 0.12507092650048435
typography_spectrum: 0.24902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf6f7'
    - '#68a5fe'
    - '#3b71eb'
    - '#2c2219'
    - '#b1b787'
  brandStrength: 1
  lightness: 0.26375954900868237
  saturation: 0.6521854093298316
  rhythmicContrast: 0.8041013216134161
purpose: []
